### ISSUE TITLE
selection.background 

### ISSUE THREAD

**Issue by cosmicethics** [hkmix/vscode-solarized-dark-vim#2]
the vscode's theme document: selection.background: Background color of text selections in the workbench (for input fields or text areas, does not apply to selections within the editor and the terminal).
Current selection.background:#073642, 
it's the  same as the background color of input fields or text areas,
when the text is selected, it looks as if it is not selected.
We can change it to #91a1a180.

**Comment by hkmix** [comment]
Ah, I'm sorry, meant to address this and totally forgot. I'll have a look at this sometime this week or weekend and fix it, thanks!
