### ISSUE TITLE
Hint colors

### ISSUE THREAD

**Issue by RuvendeGroote** [hkmix/vscode-solarized-dark-vim#3]
Hi, first of all, I love the theme, it's way more accurate (and better) than the included one.

I have one request, but it might be intended this way: the type 'hints' (not sure what they are called) are quite distracting from the actual code right now in my opinion.

<img width="356" alt="image" src="https://user-images.githubusercontent.com/14349484/221940314-1881185b-3dc5-45fb-8ecd-975201f2cccc.png">

If you look at the following theme, they are still present but a lot more subtle, which I personally prefer.

<img width="356" alt="image" src="https://user-images.githubusercontent.com/14349484/221941682-3b915a3f-c966-4e31-a2fe-9517121a8410.png">

Would be nice if we have something similar here but I also understand that some people might prefer the 'louder' version.

Anyways, thanks for developing the theme.

**Comment by hkmix** [comment]
Ah right, I typically have these off which is why I haven't properly-themed these. I'll take a look at tweaking this in the next few days, thanks for reporting!

**Comment by hkmix** [comment]
I've published version 0.2.9 which addresses this (looks like a comment) and also happens to include a number of local changes I had for awhile. Feel free to let me know if you have any thoughts!

**Comment by RuvendeGroote** [comment]
> I've published version 0.2.9 which addresses this (looks like a comment) and also happens to include a number of local changes I had for awhile. Feel free to let me know if you have any thoughts!

Just updated. My only thought is that it looks exactly like I had in mind right now. Thanks a bunch!
